---
- name: Testing playbook
  hosts: all
  gather_facts: no
  tasks:
    - name: remove directory
      ansible.builtin.file:
        path: "/opt/eetest/"
        state: absent

    - name: create directory
      ansible.builtin.file:
        path: "/opt/eetest/"
        state: directory
        mode: 0755